const fs = require("fs");
const lines = [
  "const express = require(\"express\");",
  "const router = express.Router();",
  "const COINGECKO_BASE = \"https://api.coingecko.com/api/v3\";",
  "router.get(\"/coins\", async (req, res) => {",
  "  try {",
  "    const url = COINGECKO_BASE + \"/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false\";",
  "    const response = await fetch(url);",
  "    const data = await response.json();",
  "    if (!Array.isArray(data)) {",
  "      return res.status(429).json({ error: \"CoinGecko rate limit hit. Try again in 60 seconds.\" });",
  "    }",
  "    const coins = data.map((coin) => ({",
  "      id: coin.id,",
  "      name: coin.name,",
  "      symbol: coin.symbol.toUpperCase(),",
  "      image: coin.image,",
  "      currentPrice: coin.current_price,",
  "      priceChange24h: coin.price_change_percentage_24h,",
  "      marketCap: coin.market_cap,",
  "    }));",
  "    res.json(coins);",
  "  } catch (error) {",
  "    console.error(\"Coins route error:\", error.message);",
  "    res.status(500).json({ error: \"Failed to fetch coins\" });",
  "  }",
  "});",
  "router.get(\"/prices/:coin\", async (req, res) => {",
  "  const coin = req.params.coin;",
  "  try {",
  "    const priceUrl = COINGECKO_BASE + \"/simple/price?ids=\" + coin + \"&vs_currencies=usd&include_24hr_change=true\";",
  "    const priceResponse = await fetch(priceUrl);",
  "    const priceData = await priceResponse.json();",
  "    if (!priceData[coin]) {",
  "      return res.status(404).json({ error: \"Coin not found\" });",
  "    }",
  "    const historyUrl = COINGECKO_BASE + \"/coins/\" + coin + \"/market_chart?vs_currency=usd&days=7&interval=daily\";",
  "    const historyResponse = await fetch(historyUrl);",
  "    const historyData = await historyResponse.json();",
  "    const history = historyData.prices.map(([timestamp, price]) => ({",
  "      date: new Date(timestamp).toLocaleDateString(\"en-US\", { month: \"short\", day: \"numeric\" }),",
  "      price: parseFloat(price.toFixed(2)),",
  "    }));",
  "    res.json({ coin, currentPrice: priceData[coin].usd, priceChange24h: priceData[coin].usd_24h_change, history });",
  "  } catch (error) {",
  "    console.error(\"Prices route error:\", error.message);",
  "    res.status(500).json({ error: \"Failed to fetch prices\" });",
  "  }",
  "});",
  "module.exports = router;"
];
fs.writeFileSync("routes/crypto.js", lines.join("\n"));
console.log("crypto.js fixed!");
